name: Cephas
version: 1.0
main: com.random.mob.cephas.Cephas
authors: [ cephas ]
description: Seen
commands:
  randmob:
    description: spawn a random mob at the player.
    usage: /<command>
    aliases: randommob
